<?php
/**
 * @file
 * pocam_extract.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function pocam_extract_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['current_search-standard'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'standard',
    'module' => 'current_search',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ochabasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ochabasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-7TqCFBUvppfBoYrlTYxf0VxXrnz4llZ7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7TqCFBUvppfBoYrlTYxf0VxXrnz4llZ7',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ochabasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ochabasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-h3E804ufRqmwuxTFodspV21rBJb00L2X'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'h3E804ufRqmwuxTFodspV21rBJb00L2X',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ochabasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ochabasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-jMt8phZnpIgZZNTtJ71tATNsoZgFxqKb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jMt8phZnpIgZZNTtJ71tATNsoZgFxqKb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ochabasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ochabasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
