name: Docker Dev Image

on:
  push:
    branches:
      - develop
  
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unocha/pocam-site:develop
